language: python
sudo: required

python:
 - "3.4"
 - "3.5"
 - "3.6"
before_install:
 - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
 - pip install -r requirements.txt
 - pip install coveralls
script:
 - py.test
#after_success:
# coveralls
